### ISSUE TITLE
Bundle 'App' does not exist.

### ISSUE THREAD

**Issue by vertisan** [handcraftedinthealps/ElasticsearchBundle#15]
Staring from Symfony 4, bundle conception has been rejected and is no longer used so how can I create mappings without it?  

* Symfony 5.1
* ElasticSearch 7.1
* This bundle 5.2.6.6

**ongr_elasticsearch.yaml**
```yaml
ongr_elasticsearch:
    managers:
        default:
            index:
                index_name: book
                hosts:
                    - '%env(ELASTICSEARCH_URL)%'
            mappings:
                - App
```
**services.yaml**
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $manager: '@es.manager'
```
**BookController.php**
```php
class BookController extends AbstractController
{
    /**
     * @Route("/book_popularity", methods={"GET"})
     */
    public function getPopularBooks(Request $request, Manager $manager)
    {
        $repo = $manager->getRepository(Book::class);
        $search = $repo->createSearch();

        $query = new TermQuery('title', 'Harry Potter');
        $search->addQuery($query);

        $result = $repo->findDocuments($search);

        return new JsonResponse($result);
    }
}
```
**Book.php**
```php
/**
 * @ES\Document(type="ms_card_event")
 */
class Book
{
    /**
     * @ES\Property(type="text")
     */
    protected string $title;
    // constructor, getter & setterr
}
```

Without mapping I don't getting any results.
